version: "3.7"

services:
  api:
    build: ./server
    image: node-app
    read_only: true
    container_name: api
    restart: always
    dns:
      - 1.1.1.1
    ports:
      - '5000:5000'
    environment:
      - MONGOURI=mongodb://mongodb:27017/RJD
      - DefaultPass=x+Ku1?n.ypg8BCGjWb>f
      - JWTSECRET=yzwDw_fi+Y@wc7,^=eb1?.rkVUU>.n
    depends_on:
      - mongodb
    networks:
      - node-network

  adminka:
    build: ./adminka
    image: react-adminka
    read_only: false
    container_name: react-adminka
    restart: "no"
    stdin_open: true
    tty: true
    ports:
      - '8080:8080'
    depends_on:
      - api
    networks:
      - node-network

  client:
    build: ./client
    image: react-client
    read_only: false
    container_name: react-client
    restart: "no"
    stdin_open: true
    tty: true
    ports:
      - '5000:5000'
    depends_on:
      - api
    networks:
      - node-network


  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - node-network

networks:
  node-network:
    driver: bridge